In [1]:
from Quantamental_functions import *

%load_ext autoreload
%autoreload 2

In [2]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.options.display.max_columns = 99999

In [3]:
start_year, end_year = 2019, 2024
start_date = datetime(start_year, 1, 1)
end_date = datetime(end_year, 4, 1)
bond_ticker = "^IRX"
bond_yield = get_data(bond_ticker, start_date, end_date) / 100
company_info = fetch_company_info()

[*********************100%%**********************]  1 of 1 completed

In [4]:
frames_file = process_data(start_year, end_year)
frames_data = load_pickle(frames_file)
#frames_data = load_pickle('frames_data.pkl')

In [5]:
frames_df_file = process_cik_data(frames_data, bond_yield, start_date, end_date)
frames_df = load_pickle(frames_df_file)
#frames_df = load_pickle('frames_df_file.pkl')

In [6]:
user_title = input("Enter the company name: ").upper()
filtered_companies = company_info[company_info['title'].str.contains(user_title, na=False)]
filtered_companies

    cik_str ticker         title
76  1166691  CMCSA  COMCAST CORP

In [7]:
user_cik = input("Enter the CIK: ")
show_ticker_from_cik(user_cik, api_df=frames_df)

CIK: 1166691
CMCSA cannot be classified due to insufficient data.

,basic earnings per share,capex,cash flow from financing,cash flow from investing,cash flow from operations,change in cash,depreciation and amortisation,diluted earnings per share,income before income taxes,net income,operating income,total non operating expenses,total revenues,marketable securities,accrued expenses and other,bond_yield,eps growth rate,intrinsic value
2019-03-31,0.78,2092000000.00,-4325000000.00,-3226000000.00,7231000000.00,-312000000.00,3320000000.00,0.77,4708000000.00,3553000000.00,5182000000.00,676000000.00,26859000000.00,0,0,0.02,0.00,1237.03
2019-06-30,0.69,2263000000.00,0.00,0.00,0.00,0.00,3276000000.00,0.68,4164000000.00,3125000000.00,5356000000.00,-55000000.00,26858000000.00,0,0,0.02,-0.12,1215.36
2019-09-30,0.71,2511000000.00,0.00,0.00,0.00,0.00,3180000000.00,0.70,4063000000.00,3217000000.00,5340000000.00,-110000000.00,26827000000.00,0,0,0.02,0.03,1489.33
2019-12-31,0.69,0.00,0.00,0.00,0.00,0.00,0.00,0.68,0.00,3162000000.00,5247000000.00,0.00,28398000000.00,0,0,0.02,-0.03,1678.47
2020-03-31,0.47,1881000000.00,374000000.00,-3101000000.00,5824000000.00,3020000000.00,3264000000.00,0.46,2924000000.00,2147000000.00,4852000000.00,-716000000.00,26609000000.00,0,0,0.00,-0.32,52981.18
2020-06-30,0.65,2076000000.00,0.00,0.00,0.00,0.00,3264000000.00,0.65,3955000000.00,2988000000.00,4647000000.00,420000000.00,23715000000.00,0,0,0.00,0.41,19757.49
2020-09-30,0.44,2387000000.00,0.00,0.00,0.00,0.00,3320000000.00,0.44,2770000000.00,2019000000.00,4076000000.00,-86000000.00,25532000000.00,0,0,0.00,-0.32,17888.29
2020-12-31,0.74,0.00,0.00,0.00,0.00,0.00,0.00,0.73,0.00,3380000000.00,3918000000.00,0.00,27708000000.00,0,0,0.00,0.66,48516.92
2021-03-31,0.00,1859000000.00,-1898000000.00,-2612000000.00,7751000000.00,3208000000.00,3362000000.00,0.00,4411000000.00,3329000000.00,5039000000.00,390000000.00,27205000000.00,0,0,0.00,-1.00,0.00
2021-06-30,0.00,2144000000.00,0.00,0.00,0.00,0.00,3383000000.00,0.00,5630000000.00,3738000000.00,5507000000.00,1216000000.00,28546000000.00,0,0,0.00,0.00,0.00
2021-09-30,0.00,2142000000.00,0.00,0.00,0.00,0.00,3478000000.00,0.00,5166000000.00,4035000000.00,5450000000.00,766000000.00,30298000000.00,0,0,0.00,0.00,0.00
2021-12-31,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00
2022-03-31,0.00,1856000000.00,-4490000000.00,-2597000000.00,7257000000.00,135000000.00,3548000000.00,0.00,4764000000.00,3549000000.00,5569000000.00,188000000.00,31010000000.00,0,0,0.00,0.00,0.00
2022-06-30,0.00,2414000000.00,0.00,0.00,0.00,0.00,3468000000.00,0.00,4502000000.00,3396000000.00,6367000000.00,-897000000.00,30016000000.00,0,0,0.02,0.00,0.00
2022-09-30,0.00,2791000000.00,0.00,0.00,0.00,0.00,3333000000.00,0.00,-3652000000.00,-4598000000.00,-2425000000.00,-266000000.00,29849000000.00,0,0,0.03,0.00,0.00
2022-12-31,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0,0,0.04,0.00,0.00
2023-03-31,0.00,2664000000.00,-3082000000.00,-3370000000.00,7228000000.00,796000000.00,3777000000.00,0.00,5243000000.00,3834000000.00,5646000000.00,607000000.00,29691000000.00,0,0,0.05,0.00,0.00
2023-06-30,0.00,0.00,0.00,0.00,0.00,0.00,3538000000.00,0.00,5726000000.00,4248000000.00,6709000000.00,15000000.00,30513000000.00,0,0,0.05,0.00,0.00
2023-09-30,0.00,0.00,0.00,0.00,0.00,0.00,3493000000.00,0.00,5465000000.00,4046000000.00,6475000000.00,50000000.00,30115000000.00,0,0,0.05,0.00,0.00
2023-12-31,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0,0,0.05,0.00,0.00
2024-03-31,0.00,2630000000.00,-4023000000.00,-3511000000.00,7848000000.00,304000000.00,3551000000.00,0.00,5105000000.00,3857000000.00,5810000000.00,298000000.00,0.00,0,0,0.05,0.00,0.00

In [8]:
defensive_frames, enterprising_frames, ncav_frames = classify_multiple_ciks(frames_df.keys(), 'frames', api_df=frames_df)

display(defensive_frames)
display(enterprising_frames)
display(ncav_frames)

Empty DataFrame
Columns: [Defensive Assets]
Index: []

Empty DataFrame
Columns: [Enterprising Assets]
Index: []

Empty DataFrame
Columns: [NCAV Assets]
Index: []